name: Release

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  
on:
  push:
    branches: 
     - main
  workflow_dispatch:


jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Validate semver
        run: |
          TAG=$(echo $GITHUB_REF | grep -o "[0-9][\.].*")
          CHART_VERSION=$(yq r chartName/Chart.yaml version)
          echo Current chart version $CHART_VERSION
          echo Current Tag $TAG
          semver equal $CHART_VERSION $TAG
          
      - name: Push helm chart to ghcr.io
        run: |
          cd charts
          helm package api-aks-testing
          PKG_NAME=`ls *.tgz`
          helm push ${PKG_NAME} oci://ghcr.io/${{ github.repository_owner }}/charts
      
          
